 SELECT EMPLOYEE.Fname, EMPLOYEE.Minit, EMPLOYEE.Lname, EMPLOYEE.Ssn, EMPLOYEE.Dno, DEPARTMENT.Dname FROM EMPLOYEE INNER JOIN DEPARTMENT ON EMPLOYEE.Dno=DEPARTMENT.Dnumber WHERE Ssn IN
(SELECT Mgr_ssn FROM DEPARTMENT WHERE Dnumber IN
(SELECT DISTINCT Dno FROM EMPLOYEE WHERE Ssn IN
(SELECT Essn FROM WORKS_ON GROUP BY Essn HAVING SUM(Hours)<40.0))); 